2018-12-20 19:49:30,413 ERROR: Exception on /index [GET] [in d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\Experiments\Python\SampleFlaskApplication\app\routes.py", line 36, in index
    return render_template('index.html', title='Explore', posts=posts, next_url=next_url, prev_url=prev_url)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\experiments\python\sampleflaskapplication\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Experiments\Python\SampleFlaskApplication\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Experiments\Python\SampleFlaskApplication\app\templates\base.html", line 52, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Experiments\Python\SampleFlaskApplication\app\templates\index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2018-12-20 19:50:09,854 INFO: Microblog startup [in D:\Experiments\Python\SampleFlaskApplication\app\__init__.py:41]
